destination: ./_site
permalink: /posts/:year/:month/:day/:title
url: http://blog.sebnow.co

title: "Sebastian Nowicki's Blog"
description: "Thoughts about junk and stuff, or, whatever."
author:
    name: Sebastian Nowicki
    twitter: sebnow
    github: sebnow

social:
  links:
    - https://twitter.com/sebnow
    - https://github.com/sebnow

disqus:
    shortname: sebastiannowicki
google_analytics: UA-29698241-2
gtm_container_id: GTM-MDS722W

gems:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
