destination: ./_site
permalink: /posts/:year/:month/:day/:title
url: https://blog.sebnow.co

title: "slog"
description: "Thoughts about junk and stuff, or, whatever."
author:
  name: Sebastian Nowicki
  twitter: sebnow
  github: sebnow
twitter:
  username: sebnow

disqus:
    shortname: sebastiannowicki
gtm_container_id: GTM-MDS722W
adsense_client: ca-pub-1110331206949996

gems:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
