destination: ./_site
permalink: /:year/:month/:day/:title
url: http://blog.sebnow.co

author: Sebastian Nowicki
description: "Thoughts about junk and stuff, or, whatever."
github_username: sebnow
twitter_username: sebnow

theme: minima
disqus:
    shortname: sebastiannowicki
google_analytics: UA-29698241-2

gems:
    - jekyll-feed
