destination: ./_site
permalink: /:year/:month/:day/:title

author: Sebastian Nowicki
description: "Thoughts about junk and stuff, or, whatever."

theme: minima
disqus:
    shortname: sebastiannowicki
google_analytics: UA-29698241-2
