#!/usr/bin/env bash

root=$(cd $(dirname $0)/..; pwd)
docker run --rm \
  --volume="jekyll_cache:/usr/local/bundle" \
  --volume="$root:/srv/jekyll" \
  -p 4000:4000 \
  -it jekyll/jekyll:3.8 \
  jekyll $@
